name: automata
description: A dart package to create finite state machines and state charts.
version: 0.1.0
repository: https://github.com/rows/automata
homepage: https://github.com/rows/automata/wiki
issue_tracker: https://github.com/rows/automata/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  meta: ^1.7.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.20.1
  rows_lint: ^0.1.0
  mocktail: ^0.2.0