name: pull-request

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup dart
      uses: dart-lang/setup-dart@v1

    - name: Get dependencies
      run: dart pub get

    - name: Get example dependencies
      run: dart pub get
      working-directory: example

    - name: Run formatter
      run: dart format --set-exit-if-changed .
    
    - name: Run analyzer
      run: dart analyze .

    - name: Run unit tests
      run: dart test